# Extra autostart processes
# exec-once = uwsm app -- my-service
exec-once = uwsm app -- syncthing
# exec-once = hyprshell run &
# Launch snappy-switcher https://github.com/OpalAayan/snappy-switcher
exec-once = snappy-switcher --daemon
