# Application bindings
bindd = SUPER ALT, RETURN, Tmux, exec, uwsm-app -- xdg-terminal-exec --dir="$(omarchy-cmd-terminal-cwd)" tmux new
$terminal = uwsm app -- $TERMINAL
$browser = omarchy-launch-browser

bindd = SUPER, RETURN, Terminal, exec, $terminal --dir="$(omarchy-cmd-terminal-cwd)"
bindd = SUPER SHIFT, RETURN, Browser, exec, omarchy-launch-browser
bindd = SUPER SHIFT, F, File manager, exec, uwsm app -- nautilus --new-window
bindd = SUPER SHIFT, B, Browser, exec, $browser
bindd = SUPER SHIFT ALT, B, Browser (private), exec, $browser --private
bindd = SUPER SHIFT, M, Music, exec, omarchy-launch-or-focus spotify
bindd = SUPER SHIFT, N, Editor, exec, omarchy-launch-editor
bindd = SUPER SHIFT, T, Activity, exec, omarchy-launch-tui btop
bindd = SUPER SHIFT, D, Docker, exec, omarchy-launch-tui lazydocker
bindd = SUPER SHIFT, G, Signal, exec, omarchy-launch-or-focus signal "uwsm app -- signal-desktop"
bindd = SUPER SHIFT, O, Obsidian, exec, omarchy-launch-or-focus obsidian "uwsm app -- obsidian -disable-gpu --enable-wayland-ime"
bindd = SUPER SHIFT, slash, Passwords, exec, uwsm app -- 1password

# If your web app url contains #, type it as ## to prevent hyperland treat it as comments
bindd = SUPER SHIFT, A, ChatGPT, exec, omarchy-launch-webapp "https://chatgpt.com"
bindd = SUPER SHIFT ALT, A, Grok, exec, omarchy-launch-webapp "https://grok.com"
bindd = SUPER SHIFT, C, Calendar, exec, omarchy-launch-webapp "https://app.hey.com/calendar/weeks/"
bindd = SUPER SHIFT, E, Email, exec, omarchy-launch-webapp "https://app.hey.com"
bindd = SUPER SHIFT, Y, YouTube, exec, omarchy-launch-or-focus-webapp YouTube "https://youtube.com/"
bindd = SUPER SHIFT ALT, G, Telegram, exec, omarchy-launch-or-focus Telegram "uwsm app -- telegram-desktop"
bindd = SUPER SHIFT CTRL, G, Google Messages, exec, omarchy-launch-or-focus-webapp "Google Messages" "https://messages.google.com/web/conversations"
bindd = SUPER SHIFT, X, X, exec, omarchy-launch-webapp "https://x.com/"
bindd = SUPER SHIFT ALT, X, X Post, exec, omarchy-launch-webapp "https://x.com/compose/post"

# Overwrite existing bindings, like putting Omarchy Menu on Super + Space
# unbind = SUPER SHIFT, SPACE
# bindd = SUPER SHIFT, SPACE, Omarchy menu, exec, omarchy-menu

# Move the Omarchy menu on Super + Alt (instead of Super + Alt + Space). This is due to espanso having a shortcut
# on Alr + Space which gets triggered when opening the Omarchy menu.
unbind = SUPER ALT, SPACE
bindd = SUPER, Z, Omarchy menu, exec, omarchy-menu

unbind = SUPER SHIFT, E
bindd = SUPER SHIFT, E, Email, exec, omarchy-launch-or-focus  thunderbird
bindd = SUPER SHIFT ALT, E, Protonmail, exec, omarchy-launch-webapp "https://mail.proton.me/u/0/inbox"
bindd = SUPER SHIFT CTRL, E, Gmail, exec, omarchy-launch-webapp "https://mail.google.com/mail/u/0/"
bindd = SUPER SHIFT, R, Outlook IKEA, exec, omarchy-launch-webapp "https://outlook.office.com/mail/"
bindd = SUPER SHIFT, H, Slack, exec, omarchy-launch-or-focus slack
unbind = SUPER SHIFT, C
bindd = SUPER SHIFT, C, Calendar, exec, omarchy-launch-webapp "https://calendar.proton.me/u/0/"
unbind = SUPER SHIFT, O
bindd = SUPER SHIFT, O, Standard Notes, exec, omarchy-launch-or-focus standard-notes "uwsm app -- standard-notes --no-sandbox %U"
bindd = SUPER, Next, Next workspace, workspace, e+1
bindd = SUPER, Prior, Previous workspace, workspace, e-1
# Display brightness based on https://bbs.archlinux.org/viewtopic.php?id=303898
# bindel = ,XF86MonBrightnessUp, exec, brightnessctl s 10%+
# bindel = ,XF86MonBrightnessDown, exec, brightnessctl s 10%-

# unbind ALT (SHIFT) TAB since the functionality is handled in Hyprshell instead
unbind = ALT, TAB
unbind = ALT SHIFT, TAB
bind = ALT, TAB, exec, snappy-switcher next
bind = ALT SHIFT, TAB, exec, snappy-switcher prev
