[[language]]
name = "bash"
file-types = ["sh", "bash", "zsh", ".bash_login", ".bash_logout", ".bash_profile", ".bashrc", ".profile", ".zshenv", ".zlogin", ".zlogout", ".zprofile", ".zshrc", "APKBUILD", "PKGBUILD", "eclass", "ebuild", "bazelrc", "buildfile", "sh.tmpl"]

[[language]]
name = "html"
roots = [".git"]
language-servers = ["emmet-lsp"]

[[language]]
name = "ruby"
formatter = { command = "bundle", args = ["exec", "rubocop", "-a", "--stdin", "foo.rb", "--stderr", "--fail-level", "fatal"] }
auto-format = true

[language-server.solargraph]
config = { diagnostics = true, formatting = false }

[language-server.emmet-lsp]
command = "emmet-language-server"
args = ["--stdio"]

